### ISSUE TITLE
Lockscreen does not work

### ISSUE THREAD

**Issue by nekohayo** [decathorpe/elementary-stable-rpms#9]
With pantheon-session, even though it is configured to lock the screen "on sleep" and "when screen turns off", when coming back from those states the screen is not protected by any password lockscreen.

Furthermore, calling Super+L or using the top-right corner menu to manually lock the screen does not do anything.

**Comment by nekohayo** [comment]
Oh and I'm using GDM as the login screen manager, for what it's worth (as the Pantheon session conveniently proposed itself as a choice there when I installed it); it would make sense to reuse it for the lockscreen too?

**Comment by decathorpe** [comment]
At the moment, the session locking code in the Pantheon session assumes the session was started from a lightdm greeter, and issues the DBus screen lock command according to that.

Detecting the Display Manager (lightdm / gdm) which was used to start the session is not implemented (yet), but could be added in the future.

Until then, screen locking won't work properly when starting the Pantheon session from gdm - but I'll keep this issue open, since this should be considered a security risk and should definitely be fixed at some point in the future.

**Comment by nekohayo** [comment]
Filed a bug upstream at https://bugs.launchpad.net/gala/+bug/1649713 but got no reaction, maybe the wrong component?

**Comment by decathorpe** [comment]
Hmm. I think the code that needs to be changed is in `wingpanel-indicator-session`, as that dispatches the DBus call to the screen locker. I think it would be possible to check which DBus service is running (gdm or light-locker) and dispatch DBus calls accordingly, but I have no experience with programming in Vala (and using DBus at all) ... but I can look into it myself if I have the time.

**Comment by nekohayo** [comment]
Interestingly enough... it doesn't work with lightdm either. If I stop gdm using systemctl and start lightdm, and take extreme care to log into Pantheon (instead of GNOME) with it, it is still unable to do screen locking, even when asked explicitly from the top-right menu.

**Comment by decathorpe** [comment]
Yep. That's strange.

**Comment by CameronNemo** [comment]
Locking the session with lightdm requires a component called `light-locker`, IIRC. Can you try installing that and then attempting to lock the screen?

**Comment by decathorpe** [comment]
Probably my pantheon-greeter package should also pull in `light-locker` as a dependency. Right now, it's only pulled in by the switchboard settings panel that configures the lock screen (`switchboard-plug-security-privacy`).

**Comment by nekohayo** [comment]
I don't think that's the absence of the package was the cause, as it was already installed on my system...

**Comment by Bakan0** [comment]
Anyway I can help? Running Fedora25

**Comment by decathorpe** [comment]
@Bakan0 can you confirm the issue? if yes, can you help with debugging?

**Comment by Bakan0** [comment]
100% confirmed. I cannot lock my screen using the Lock option in Power menu. I would be more than happy to help with debugging, although I'm not sure specifically what you want me to do, as I am a beginner/novice when it comes to linux in general.

I've also noticed (I'm sure you already know) that the "System" Tab/Area does not exist in my Settings > Keyboard > Shortcuts options (to try to modify the Lock Screen shortcut).

**Comment by decathorpe** [comment]
Which display manager are you using? GDM or LightDM? If LightDM, which greeter?

**Comment by Bakan0** [comment]
@decathorpe GDM

**Comment by decathorpe** [comment]
Good, I supsected that might be the case. The pantheon session doesn't lock correctly when run under GDM.

Would it be possible for you to try it with lightdm + the lightdm "gtk" greeter?

**Comment by Bakan0** [comment]
Ok. I am currently using lightdm gtk greeter and logging into pantheon. still no lock.

**Comment by decathorpe** [comment]
Thanks for confirming this issue. I'll look at the source code when I have some time, maybe I can pinpoint the issue.

**Comment by CameronNemo** [comment]
@Bakan0 @nekohayo 

Would you mind trying to lock the screen using command line tools while using lightdm and ensuring that light-locker is installed and running?

Check to see that light-locker is running:

    ps aux | grep light-locker

If the process does not appear then light-locker has not been started for some reason. Please report this, and start it manually for the following commands.

First use the `lightdm` provided tool:

    dm-tool lock

then use the `light-locker` provided tool:

    light-locker-command --lock

If either of these commands fails, please report back. If they both succeed then the problem is in how the indicator is triggering light-locker.

**Comment by nekohayo** [comment]
```
$ ps aux | grep dm
root      1140  0.0  0.0 357208  6596 ?        SLsl 12:12   0:00 /usr/sbin/lightdm
root      1157  4.6  0.8 446068 66640 tty1     Ssl+ 12:12   0:12 /usr/libexec/Xorg -background none :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt1 -novtswitch
root      1427  0.0  0.1 285124  8164 ?        Sl   12:13   0:00 lightdm --session-child 12 21

$ ps aux | grep light-locker
[no results]

$ sudo dnf install light-locker
Package light-locker-1.7.0-2.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

$ light-locker
** (light-locker:2682): WARNING **: screensaver already running in this session
```

```
$ dm-tool lock
```
Result: my screen gets locked by getting thrown back to lightdm's login screen instantly; I can then re-login and continue

```
$ light-locker-command --lock
```
No effect.

**Comment by nekohayo** [comment]
Pretty sure it's a conflict in screensavers that is causing the issue, given that the screen never ever turns off to power saving mode either.

**Comment by nekohayo** [comment]
Any new findings on this @decathorpe ?

**Comment by decathorpe** [comment]
Sorry, no ... I have to admit that this issue has pretty low priority for me right now, since I am not knowledgeable enough (with lightdm etc.) to fix it myself, and nobody else volunteered to investigate further.

**Comment by nekohayo** [comment]
Do you mean that it actually works for you with lightdm? It doesn't on my side even with lightdm...

(If it doesn't work for you either, I'm surprised you've been OK with having a broken screen lock for all this time :)

**Comment by decathorpe** [comment]
I checked earlier today, and it's not working here, either.
I'm not using a Pantheon session as my primary desktop (I only fire it up for testing from time to time in a VM, since it doesn't even work on f26 right now), so it's not a problem for me ...

**Comment by nekohayo** [comment]
>  I'm not using a Pantheon session as my primary desktop (I only fire it up for testing from time to time in a VM, since it doesn't even work on f26 right now), so it's not a problem for me ...

Well... I upgraded from F25 to F26 and the Pantheon session still works fine. Maybe it's time for you to dogfood again ;)

**Comment by decathorpe** [comment]
Well, it works again - because I fixed it on f26 a few weeks ago ;)

**Comment by nekohayo** [comment]
Is there anything I can do to help with this? Hell, if I have to try to semi-amateurishly hack code, I could even give that a try, I just 1) have no idea where to look at all 2) have no skills building anything elementary 3) have zero packaging skills

**Comment by decathorpe** [comment]
I am not sure which component is responsible for the lock screen not working. However, light-locker is the program which should lock the screen on LightDM, and wingpanel-indicator-session should invoke the call to lock the session. pantheon-greeter also has some issues on f26+, but we're already debugging that.

**Comment by CameronNemo** [comment]
Based on the feedback nekohayo gave, I think the problem is that light-locker is not locking the screen properly. If you want to debug further, I would recommend looking there. GNOME screensaver can interfere with light-locker's operation, so make sure that is uninstalled.

**Comment by CameronNemo** [comment]
Also -- light-locker was running while you issued the `light-locker-command --lock`, correct?

**Comment by nekohayo** [comment]
Yep, light-locker was running back then, and was still running when I tested again today with the same results (```dm-tool lock``` works, but ```light-locker-command --lock``` doesn't*)

*: you now get an error message instead of just no output:
```
$ light-locker-command --lock
** Message: Received error message from the locker:
   GDBus.Error:org.freedesktop.DBus.Error.NotSupported:
   This method is not implemented
```

Nonetheless... gnome-screensaver was not even installed (the package for it in F26 is numbered 3.6, so apparently this is a long-deprecated component), so it can't be the one interfering (and again, I was testing with lightdm, with gdm disabled from starting through systemd, after a full reboot)

**Comment by CameronNemo** [comment]
Check out the-cavalry/light-locker#97. It's the same message.

**Comment by raymanfx** [comment]
FYI, this should make it work with GDM: https://vomitb.in/bDKo4Yd9ss.
I have a better patch which can detect gnome-screensaver or light-locker, but that still needs some cleanup, I only started learning Vala today.

I compiled libsession from wingpanel-indicator-session-2.0.1, but replacing the libsession in /usr/lib64/wingpanel resulted in wingpanel not being able to start anymore, probably some local issue here.

**Comment by decathorpe** [comment]
Depending on gnome-screensaver is not a good idea, it's not supported on fedora anymore and has not seen new releases for over 5 years.

**Comment by raymanfx** [comment]
This was intended as a POC and is tailored to my needs (I'm using gnome-screensaver on my machine). It should be easy for you to fix the issue now (or you can wait until I do it).

**Comment by raymanfx** [comment]
Hmm, actually, after doing further research, I think locking the screen via GDM using D-Bus is impossible.
So pantheon-session should probably either (strongly) recommend replacing GDM with LightDM (so you can use light-locker) or it should recommend gnome-screensaver and start it on session start and call that via D-Bus instead.

Option 2) requires a patch to wingpanel-indicator-session but might be preferable since we don't mess with the default Fedora Display Manager in that case.

**Comment by decathorpe** [comment]
1) Locking the screen with light-locker on LightDM doesn't work (that's the original issue!), so that is a non-starter. Either way, forcing people to replace the default DM to be able to lock the screen isn't a good solution either. This might only become a working solution once there is a Pantheon spin of fedora where we can default to LightDM. However, that can only happen once screen locking works, and it doesn't help people who install Pantheon as their second DE.

2) Depending on 5-year-old, possibly broken and/or insecure software to do so sounds like a terrible idea.

There must be something else going on, because not even system-logind can lock the session (with `loginctl lock-session XXX` ...

**Comment by raymanfx** [comment]
Ah, I didn't know it was broken even on LightDM, probably skimmed that passage. Though, just like you said, I also detest the idea of forcing people to install a non-default display manager.

What makes you think gnome-screensaver is insecure or broken?
That's a pretty bold statement to make just because gnome-shell does not use it anymore.
The last real (non-translation) update I can find is from July 2015, so I don't see where you get the "5-years-old" from?

If you see any glaring problems with gnome-screensaver I am happy to look into those. I'm rather well versed in C/C++ (more so than Vala/GTK anyway) so I should be able to at least assist in fixing those problems.

**Comment by decathorpe** [comment]
The last real update the gnome-screensaver package in fedora got was this:

```
* Tue Oct 16 2012 Kalev Lember <kalevlember@gmail.com> - 3.6.1-1
- Update to 3.6.1
```

All subsequent builds were just rebuilds, one compilation fix, and one crash fix.

This 3.6.1 release is the last release that was tagged upstream, and is - according to [gnome git](https://git.gnome.org/browse/gnome-screensaver/tag/?h=3.6.1) - over 5 years old.

So I assume it's safe to say that the package is outdated, and possibly abandoned upstream.

**Comment by raymanfx** [comment]
So the correct solution I see here would be someone stepping up and maintaining gnome-screensaver again? I have zero experience with Fedora packaging, but will try to get into it if nobody else is willing to.

Wingpanel-indicator-session still needs a patch then of course.

**Comment by decathorpe** [comment]
Picking up the fedora package isn't enough, the package itself is recent. Somebody needs to take over the upstream project.

**Comment by raymanfx** [comment]
I was talking about upstream maintainership. Fedora packaging was only mentioned because Fedora is all I care about, so I want to make sure it is correctly packaged and at least co-maintain the Fedora package if I take on the upstream project.

Time is limited for me right now so I'm not sure how quickly I can get into the whole Gnome project and get an overview of the whole codebase. Maybe a fork/rebrand is also a good idea because the project would not be tightly coupled with the Gnome desktop shell anymore. I still need to think about this.

**Comment by CameronNemo** [comment]
1. I don't think its an unreasonable expectation for users to switch to LightDM if they intend to use Pantheon and get the full experience. This will decrease maintenance needs over time.

2. `gnome-screensaver` maintenance is a significant burden, and at least mildly security sensitive. There are likely much better uses of one's time in getting Pantheon running well on Fedora.

**Comment by nekohayo** [comment]
Hi @raymanfx and @decathorpe, let me clarify a few things here, from my discussions with core GNOME maintainers:

* GNOME Screensaver is not used for screen locking anymore, and it's a dead module, don't use that
* In GNOME, GNOME Shell is the one doing the screen locking for anything that is UI-related, and GDM is only doing backend parts (like interacting with PAM), it does not actually provide any UI (the "UI" of GDM is actually a system session of GNOME Shell).

According to core GNOME devs, screen locking turns out to be essentially a feature of the desktop environment. Summary of the discussion:
> halfline: I will say the API between gnome-shell and GDM isn't necessarily stable; but in practice anytime i've changed it, it's bitten me because of RHEL rebases, so it probably won't be changing much in the future ;-)
> halfline: For what it's worth, gnome-shell screen locking only works with GDM, so if pantheon screen locking only works with its display manager, that would at least be par for the course
> mclasen: forcing the user to do it seems a bit unfriendly
> Jeff: so lemme just check if my understanding is correct: does gnome-shell "ask" gdm to do the locking nowadays, or is gnome-shell implementing its own screen locking "on top" of gdm that could already do its own screen locking?
> halfline: GDM is the backend that talks to PAM ; gnome-shell is the front end that talks to the user. gnome-shell has a "shield" that blocks the screen, so screen locking is implemented by gnome-shell, but password checking is implemented by GDM and the lower layers
> Jeff: aaah, so the shield and anything "user visible" is not offered by gdm
> halfline: right. That's true of the login screen too btw: login screen UI is entirely gnome-shell. GDM is only backend code, no GUI code at all (except some obscure XDMCP choooser stuff)

So in theory Pantheon could still use GDM as a backend for locking to interact with PAM etc etc., but it would need to provide the "UI" for locking (I suppose maybe that's what light-locker does in the world of lightdm?). It's possible, but I don't know if such a UI already exists ready to be plugged with the API of GDM as the backend. Maybe you can check that? Otherwise I guess that "making lightdm screen locking work with Pantheon on Fedora" may be the only other approach.

**Comment by CameronNemo** [comment]
In Pantheon on elementary OS, light-locker calls on lightdm to provide the lock screen UI. The window manager / desktop shell plays no role in the locking UI.

**Comment by decathorpe** [comment]
This issue is now also affecting what will become elementaryOS juno. The issue is tracked here: https://github.com/elementary/greeter/issues/92

**Comment by decathorpe** [comment]
So, after some debugging, the lock screen should now work - at least when running the Pantheon session atop LightDM.

`light-locker` doesn't support GDM, so that's a bug in `light-locker`, and isn't related to my packaging.
